### ISSUE TITLE
Can't enable worker mode

### ISSUE THREAD

**Issue by atachka** [reacherhq/check-if-email-exists#1551]
### What happened?

I'm trying to use bulk api which requires enabling worker mode. 

Here is the docker-compose.yaml file : 
```
version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reacher_db
    restart: always

  worker1:
    image: reacherhq/backend:beta
    container_name: worker1
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      RCH__BACKEND_NAME: worker1
      RUST_LOG: reacher=debug # Use 'debug' level logging for more details
      RCH__WORKER__ENABLE: true
      RCH__WORKER__RABBITMQ__URL: amqp://guest:guest@rabbitmq:5672
      RCH__WORKER__POSTGRES__DB_URL: postgres://postgres:postgres@postgres:5432/reacher_db
      RCH__WORKER__THROTTLE__MAX_REQUESTS_PER_DAY: 10000
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  worker2:
    image: reacherhq/backend:beta
    container_name: worker2
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      RCH__BACKEND_NAME: worker2
      RUST_LOG: reacher=debug # Use 'debug' level logging for more details
      RCH__WORKER__ENABLE: true
      RCH__WORKER__RABBITMQ__URL: amqp://guest:guest@rabbitmq:5672
      RCH__WORKER__POSTGRES__DB_URL: postgres://postgres:postgres@postgres:5432/reacher_db
      RCH__WORKER__THROTTLE__MAX_REQUESTS_PER_MINUTE: 100
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

```

the workers are stuck like this and they error 2024-12-23 15:34:18 Error: When worker mode is enabled, a Postgres database must be configured.
![Screenshot 2024-12-23 at 15 34 50](https://github.com/user-attachments/assets/7c2d7e23-3fd6-4996-9b4e-382f34abb26c)
